---
title: "Detailed diagnostics"
author: "Robert Wildermuth"
date: "2025-9-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, loadLibraries}
library(mgcv)
library(tidyr)
library(lubridate)
library(pROC)
library(ggplot2)
library(scales)
library(dplyr)
library(gbm)
library(dismo)
library(viridis)
library(sqldf)
library(caret)
source("../R/buildSDM.R")
source("../R/LeaveNOutDiags.R")
```

# Calculate some detailed SDM fit diagnostics

Load the data and split into test and training sets
```{r, loadData}
# Load biological observation data with environmental covariates extracted
# This is now updated to include variables extracted at a lag of 1 year, which are used to calculate
# persistence skill (variables labeled with "_lag1")
# Is assumed that the columns "lon", "lat", and "date" are present and complete
obs <- readRDS("../data/combinedBioObs_envExtracted.rds")
# If observations don't have a "year", "month" and "quarter" columns, add them. Will need a "date" column to get them
if(!"year" %in% colnames(obs)) {
  obs$year <- year(obs$date)  
}
if(!"month" %in% colnames(obs)) {
  obs$month <- month(obs$date)  
}
if(!"quarter" %in% colnames(obs)) {
  obs$quarter <- quarter(obs$date)  
}

# I'm missing predictor variables for 2024, so I'm trimming that year off
obs <- subset(obs, year <= 2023)
# Define the target variable: here presence/absence of anchovy
obs$pa <- obs$anchPA

# An example: 5-year forecast skill for anchovy SDM where training data include between 10 and 15 years of data 
yrsToTrain <- seq(10, 15) 
yrsToForecast <- 5

# Define the training and test forecast years
yrs <- unique(sort(obs$year)) # Years in the observational dataset
terminalYr <- max(yrs) - yrsToForecast # The last year of training data 
train <- subset(obs, year <= terminalYr)
test <- subset(obs, year > terminalYr & year <= (terminalYr + yrsToForecast)) # Observations after the training data ends


```

Do different levels of cross-validation
#!!RW: need to define these functions, or save and source them from 2_Fit_model.R
```{r, xv}
sdmType <- "brt" # Can currently be "gam" or "brt"
k <- 4 # Number of knots for a GAM. Will be ignored if not building a GAM
tc <- 3 # tree complexity for a BRT. Will be ignored if not building a BRT
lr <- 0.02 # learning rate for a BRT. Will be ignored if not building a BRT
max.trees <- 10000 # max trees for a BRT. Will be ignored if not building a BRT
varNames <- c("sst", "ild", "sst_sd", "ssh_sd", "logChl", "logEKE", "distLand", "anchssb") # Names of predictors in the SDM
targetName <- "pa" # Target variable for the SDM

# Leave-one-out cross-validation
SDR.loo.eval <-LOO_eval(DataInput=obs, gbm.x=varNames, gbm.y=targetName,lr=lr, tc=tc)

# test with 25% of the full dataset
SDR.7525.eval <- eval_7525(DataInput= obs,gbm.x=varNames, gbm.y=targetName,lr=lr, tc=tc, retainPct = 0.75)

# compare to full model fit 
#!!RW: Is this just the same as buildSDM()?
SDR.100.eval <- eval_7525(DataInput= obs,gbm.x=varNames, gbm.y=targetName,lr=lr, tc=tc, retainPct = 1)

comp75v100 <- bind_rows(SDR.7525.eval, SDR.100.eval) %>% mutate(retainPct = c(75, 100))
```