---
title: "Simple model fitting"
author: "Robert Wildermuth"
date: "2025-9-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, loadLibraries}
library(mgcv)
library(tidyr)
library(lubridate)
library(pROC)
library(ggplot2)
library(scales)
library(dplyr)
library(gbm)
library(dismo)
library(viridis)
source("../R/buildSDM.R")
source("../R/runDiagnostics.R")
```

# Fit an SDM model and calculate basic diagnostics

Load the training dataset and fit the 
```{r, fitSDM}
# Load biological observation data with environmental covariates extracted
# This is now updated to include variables extracted at a lag of 1 year, which are used to calculate
# persistence skill (variables labeled with "_lag1")
# Is assumed that the columns "lon", "lat", and "date" are present and complete
obs <- readRDS("../data/combinedBioObs_envExtracted.rds")
# If observations don't have a "year", "month" and "quarter" columns, add them. Will need a "date" column to get them
if(!"year" %in% colnames(obs)) {
  obs$year <- year(obs$date)  
}
if(!"month" %in% colnames(obs)) {
  obs$month <- month(obs$date)  
}
if(!"quarter" %in% colnames(obs)) {
  obs$quarter <- quarter(obs$date)  
}

# I'm missing predictor variables for 2024, so I'm trimming that year off
obs <- subset(obs, year <= 2023)
# Define the target variable: here presence/absence of anchovy
obs$pa <- obs$anchPA

sdmType <- "brt" # Can currently be "gam" or "brt"
k <- 4 # Number of knots for a GAM. Will be ignored if not building a GAM
tc <- 3 # tree complexity for a BRT. Will be ignored if not building a BRT
lr <- 0.02 # learning rate for a BRT. Will be ignored if not building a BRT
max.trees <- 10000 # max trees for a BRT. Will be ignored if not building a BRT
varNames <- c("sst", "ild", "sst_sd", "ssh_sd", "logChl", "logEKE", "distLand", "anchssb") # Names of predictors in the SDM
targetName <- "pa" # Target variable for the SDM
mod1 <- buildSDM(sdmType = sdmType, train = obs, varNames = varNames, targetName = targetName, 
                   k = k, tc = tc, lr = lr, max.trees = max.trees)
mod2 <- buildSDM(sdmType = "gam", train = obs, varNames = varNames, targetName = targetName, 
                   k = k, tc = tc, lr = lr, max.trees = max.trees)
summary(mod1) # If you want to check convergence etc. But GAMs/BRTs nearly always converge unless parameters v inappropriate
  # gbm.step prints model convergence progress as it goes, so you'll see if the number of trees is too small (< ~ 1500)
  
if(sdmType == "gam") {
  # For GAMS
  concurvity(mod1)
  gam.check(mod1)
}

#Percent deviance explained: SINGLE model
#((null deviance - residual deviance)/null deviance)*100
dev_eval=function(model_object){
  null <- model_object$self.statistics$mean.null
  res <- model_object$self.statistics$mean.resid
  dev=((null - res)/null)*100 
  return(dev)
}
dev_eval(mod1)# deviance explained by the model
```

## Evaluate diagnostics of model's fit to data

Calculate some basic diagnostics 
```{r, diags}
# Return some simple diagnostics
evalOutputs <- runDiagnostics(mod = mod1, max.trees = max.trees) 
evalOutputs
```

Visualize the results
```{r}
if(sdmType == "gam") {
  # For GAMs
  plot(mod1, pages = 1)
} else if(sdmType == "brt") {
  # For BRTs
  gbm.plot(mod1, smooth=TRUE, plot.layout = c(3,3), write.title=T) #response curves/ fitted functions
  
  #!!RW: From what package?
  ggInfluence(mod1) #!!RW: gives similar plot to call to summary() two sections above
}
```

Calculated the CV around model parameter estimates
```{r, calcCV}
#!!RW: Not sure if this is necessary step for all SDMs?

#We usually run the models 10 times to have the average of the evaluation metrics and predictions in case you want to include CV
#Make function to fit 10 models, and output as a list in rds format
#Observer data only
fit.brt.n10 <- function(data, varNames, targetName, k, tc, lr, max.trees, iterations){
  Species_Models <- vector("list", iterations)
  for (i in 1:iterations){
    #!!RW: replace with buildSDM()?
    model <- buildSDM(sdmType = sdmType, train = data, varNames = varNames, targetName = targetName, 
                      k = k, tc = tc, lr = lr, max.trees = max.trees)
    Species_Models[[i]] <- model
  }
  return(Species_Models)
}

#fit 10 BRT models to estimate CV
anch10models <- fit.brt.n10(data=obs,varNames = varNames, targetName = targetName, 
                            tc = tc, lr = lr, max.trees = max.trees, 
                            iterations=10)


#Get % deviance explained for 10 models
SDR_10models_evals <- as.data.frame(matrix(1,nrow=10,ncol=1))
counter <- 1
for (d in 1:10){
  eval <- (dev_eval(anch10models[[d]]))
  SDR_10models_evals[counter,1] <- eval
  counter <- counter+1
}
#!!RW: There is no variation in deviation explained. Gives bootstrap SD of 0
smryMean <- mean(SDR_10models_evals$V1)
smryMean
smrySD <- sd(SDR_10models_evals$V1)
smrySD 
```