---
title: "Simple SDM prediction"
author: "Robert Wildermuth"
date: "2025-9-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, loadLibraries}
library(mgcv)
library(tidyr)
library(lubridate)
library(pROC)
library(ggplot2)
library(scales)
library(dplyr)
library(gbm)
library(dismo)
library(viridis)
library(sqldf)
library(terra)
library(rnaturalearth)
library(sf)
source("../R/buildSDM.R")
source("../R/scoreSDM.R")
source("../R/testSkillSDM.R")
source("../R/runDiagnostics.R")
```

# Perform simple forecast predictions from an SDM model

Load the data for our previously fit SDM model
```{r, loadSDM}
# Load biological observation data with environmental covariates extracted
# This is now updated to include variables extracted at a lag of 1 year, which are used to calculate
# persistence skill (variables labeled with "_lag1")
# Is assumed that the columns "lon", "lat", and "date" are present and complete
obs <- readRDS("../data/combinedBioObs_envExtracted.rds")
# If observations don't have a "year", "month" and "quarter" columns, add them. Will need a "date" column to get them
if(!"year" %in% colnames(obs)) {
  obs$year <- year(obs$date)  
}
if(!"month" %in% colnames(obs)) {
  obs$month <- month(obs$date)  
}
if(!"quarter" %in% colnames(obs)) {
  obs$quarter <- quarter(obs$date)  
}

# I'm missing predictor variables for 2024, so I'm trimming that year off
obs <- subset(obs, year <= 2023)
# Define the target variable: here presence/absence of anchovy
obs$pa <- obs$anchPA

sdmType <- "brt" # Can currently be "gam" or "brt"
k <- 4 # Number of knots for a GAM. Will be ignored if not building a GAM
tc <- 3 # tree complexity for a BRT. Will be ignored if not building a BRT
lr <- 0.02 # learning rate for a BRT. Will be ignored if not building a BRT
max.trees <- 10000 # max trees for a BRT. Will be ignored if not building a BRT
varNames <- c("sst", "ild", "sst_sd", "ssh_sd", "logChl", "logEKE", "distLand", "anchssb") # Names of predictors in the SDM
targetName <- "pa" # Target variable for the SDM

#!!RW: do we need to load the full model data fit? What is there to compare among these outputs?
```

## Predict to previously observed locations
```{r}
# Predict at 1-year forecast horizon
horizon <- 1
  
# Call scoreSDM to build an SDM using subObs as training and test data
modH1 <- scoreSDM(subObs = obs, sdmType = sdmType, varNames = varNames,
                       targetName = targetName, k = k, tc = tc, lr = lr, max.trees = max.trees, 
                       yrsToForecast = horizon, includePersistence = TRUE)
# Call testSkillSDM to assess the skill of the X-year forecast for this SDM
aucCutoff <- 10 # If less observations than this cutoff within a month/season etc., AUC will not be calculated
sdmSkillH1 <- testSkillSDM(mod = modH1, targetName = targetName, aucCutoff = aucCutoff, usePersistence = FALSE)
# Add noYrs and sdmType to output
yrs <- unique(sort(obs$year))
sdmSkillH1$noYrsTrain <- length(yrs) - horizon
sdmSkillH1$terminalYr <- max(obs$year) - horizon 
sdmSkillH1$sdmType <- sdmType
  
# If you want to assess persistence skill, add a new list element showing sdmSkill for those predictions
sdmSkillPersH1 <- testSkillSDM(mod = modH1, targetName = targetName, aucCutoff = aucCutoff, usePersistence = TRUE)
# Add noYrs and sdmType to output
sdmSkillPersH1$noYrsTrain <- length(yrs) - horizon
sdmSkillPersH1$terminalYr <- max(obs$year) - horizon 
sdmSkillPersH1$sdmType <- sdmType
  
  
# Return some simple diagnostics
evalOutputs <- runDiagnostics(mod = modH1$sdm, max.trees = max.trees)
  
# plot the predictions and observations
  

```

What about a different forecast horizon?
```{r, horiz3}
# Predict at 3-year forecast horizon
horizon <- 3
  
# Call scoreSDM to build an SDM using subObs as training and test data
modH3 <- scoreSDM(subObs = obs, sdmType = sdmType, varNames = varNames,
                       targetName = targetName, k = k, tc = tc, lr = lr, max.trees = max.trees, 
                       yrsToForecast = horizon, includePersistence = TRUE)
# Call testSkillSDM to assess the skill of the X-year forecast for this SDM
aucCutoff <- 10 # If less observations than this cutoff within a month/season etc., AUC will not be calculated
sdmSkillH3 <- testSkillSDM(mod = modH3, targetName = targetName, aucCutoff = aucCutoff, usePersistence = FALSE)
# Add noYrs and sdmType to output
yrs <- unique(sort(obs$year))
sdmSkillH3$noYrsTrain <- length(yrs) - horizon
sdmSkillH3$terminalYr <- max(obs$year) - horizon 
sdmSkillH3$sdmType <- sdmType
  
# If you want to assess persistence skill, add a new list element showing sdmSkill for those predictions
sdmSkillPersH3 <- testSkillSDM(mod = modH3, targetName = targetName, aucCutoff = aucCutoff, usePersistence = TRUE)
# Add noYrs and sdmType to output
sdmSkillPersH3$noYrsTrain <- length(yrs) - horizon
sdmSkillPersH3$terminalYr <- max(obs$year) - horizon 
sdmSkillPersH3$sdmType <- sdmType
  
  
# Return some simple diagnostics
evalOutputs <- runDiagnostics(mod = modH3$sdm, max.trees = max.trees)

# plot the predictions and observations
```

## Predict to the full spatial surface
```{r}
nc_files <- list.files("C:/Users/r.wildermuth/Documents/CEFI/SDMClimateForecasts/inputData", 
                       pattern = "\\.nc$", full.names = TRUE)
var_names <- c("tos")

# Define raster template
r_template <- rast(extent = c(-180, 180, -90, 90), resolution = 0.25, crs = "EPSG:4326")

# Get number of time steps from first variable
test_nc <- nc_open(nc_files[1])
nt <- dim(ncvar_get(test_nc, var_names[1]))[3]


nc <- nc_open(nc_files[1])
time_raw <- ncvar_get(nc, "time")  # may be in hours/days since a start date
time_units <- ncatt_get(nc, "time", "units")$value
nc_close(nc)

# Convert time to Date
# Example: "days since 1950-01-01"
origin_str <- sub(".*since ", "", time_units)
dates <- as.Date(time_raw, origin = origin_str)


nc_close(test_nc)

# Load coastline
world <- ne_countries(scale = "medium", returnclass = "sf")

# Custom palette
pal <- colorRampPalette(c("#9b59b6", "#3498db", "#1abc9c", "#f1c40f", "#e74c3c"))
ncolors <- 100
custom_colors <- pal(ncolors)

# n_days <- nlayers(dates) # Doesn't work, also not used
i <- dim(dates)

raster_list <- list()
  
  date_str <- format(dates[i], "%Y-%m-%d")
  
  
  # for (i in seq_along(nc_files)) {
    nc <- nc_open(nc_files[1])
    varname <- var_names[1]
    var_dims <- nc$var[[varname]]$dim
    dim_names <- sapply(var_dims, function(x) x$name)
    
    # Identify lon/lat
    if ("xh" %in% dim_names) lon <- ncvar_get(nc, "xh")
    if ("xq" %in% dim_names) lon <- ncvar_get(nc, "xq")
    if ("yh" %in% dim_names) lat <- ncvar_get(nc, "yh")
    if ("yq" %in% dim_names) lat <- ncvar_get(nc, "yq")
    
    lon_mod <- ifelse(lon > 180, lon - 360, lon)
    
    # Extract time slice
    if (length(var_dims) == 2) {
      var_array <- ncvar_get(nc, varname)
    } else if (length(var_dims) == 3) {
      var_array <- ncvar_get(nc, varname, start = c(1, 1, i), count = c(-1, -1, 1))
    } else {
      stop(paste("Unsupported dimensions in", varname))
    }
    
    nc_close(nc)
    
    lon_exp <- rep(lon_mod, times = length(lat))
    lat_exp <- rep(lat, each = length(lon_mod))
    var_vec <- as.vector(var_array)
    
    points_sf <- st_as_sf(data.frame(lon = lon_exp, lat = lat_exp, var = var_vec),
                          coords = c("lon", "lat"), crs = 4326)
    
    points_vect <- vect(points_sf)
    r_var <- rasterize(points_vect, r_template, field = "var", fun = mean, background = NA)
    names(r_var) <- varname
    raster_list[[1]] <- r_var
  
  
   r_stack <- rast(raster_list)
  names(r_stack) <- c( "sst")

# assume data available in a mesh of evenly-spaced points within the sample frame

# read in example projection data


# predict_df <- read.csv("../data/example.csv")
predict_df <- as.data.frame(r_stack, xy = TRUE, na.rm = TRUE)
  predict_df_clean <- na.omit(predict_df)
  predict_df_clean$sst_lag1 <- predict_df_clean$sst
  
  # Predict
  # RW: must have all variables for prediction!
  mod1 <- buildSDM(sdmType = sdmType, train = obs, varNames = "sst", targetName = targetName, 
                   k = k, tc = 1, lr = 0.01, max.trees = max.trees)
  
  predictions <- predict(mod1, newdata = predict_df_clean[, -c(1,2)], type = "response")
  
  # Convert to spatial
  pred_df <- data.frame(x = predict_df_clean$x,
                        y = predict_df_clean$y,
                        prediction = predictions)
  pred_sf <- st_as_sf(pred_df, coords = c("x", "y"), crs = 4326)
  pred_vect <- vect(pred_sf)
  r_pred <- rasterize(pred_vect, r_template, field = "prediction")
  
 
  
  r_pred_df <- as.data.frame(r_pred, xy = TRUE, na.rm = TRUE)
  
  
  # Plot with white background
  p <- ggplot() +
    geom_raster(data = r_pred_df, aes(x = x, y = y, fill = last)) +
    geom_sf(data = world, fill = "gray80", color = "black", size = 0.3) +
    scale_fill_gradientn(name = "Prediction", colors = custom_colors, limits = c(0, 1),na.value = "transparent") +
    coord_sf(xlim = c(-130, -117), ylim = c(30, 47), expand = FALSE) +
    labs(title = paste("BRT Prediction on SST only - Day", date_str),
         x = "Longitude", y = "Latitude") +
    theme_minimal() +
    theme(
      legend.position = "bottom",
      plot.title = element_text(face = "bold", size = 16),
      panel.background = element_rect(fill = "white", color = "white"),  # Set plot background to white
      plot.background = element_rect(fill = "white", color = "white"),   
    )
p

```

## Compare the skill for each prediction
```{r, testSkill}
sdmSkillAll <- rbind(sdmSkillH1, sdmSkillH3)

# Aggregate so skills are averaged across different months/seasons. "year" is the test year
sdmSkillAgg <- aggregate(auc ~ time + space + noYrsTrain + terminalYr + year, sdmSkillAll, FUN = mean, na.rm = TRUE)
# Add a field converting year to forecast time horizon
sdmSkillAgg$forecastHorizon <- sdmSkillAgg$year - sdmSkillAgg$terminalYr

# also compare to a persistence assumption
sdmSkillPers <- rbind(sdmSkillPersH1, sdmSkillPersH3)

# Aggregate so skills are averaged across different months/seasons. "year" is the test year
sdmSkillPersAgg <- aggregate(auc ~ time + space + noYrsTrain + terminalYr + year, sdmSkillPers, FUN = mean, na.rm = TRUE)
# Add a field converting year to forecast time horizon
sdmSkillPersAgg$forecastHorizon <- sdmSkillPersAgg$year - sdmSkillPersAgg$terminalYr

  
# spatial plot of difference in prediction skill and observations
```